### one to one join

In [15]:
import pandas as pd

df1 = pd.DataFrame({
    "employee": ["Alice", "Bob", "Charlie", "David"],
    "department": ["HR", "IT", "Finance", "Finance"],
    "address": ["123 Main St", "456 Elm St", "789 Oak St", "101 Pine St"]
})

df2 = pd.DataFrame({
    "employee": ["Alice", "Bob", "Charlie"],
    "skills": [["arcitecture", "design"], ["development", "testing"], ["analysis"]],
    "salary": [50000, 60000, 70000]
})

In [4]:
df3 = pd.merge(df1,df2) # default is inner join, on the common column "employee"
df3

  employee department      address                  skills  salary
0    Alice         HR  123 Main St   [arcitecture, design]   50000
1      Bob         IT   456 Elm St  [development, testing]   60000
2  Charlie    Finance   789 Oak St              [analysis]   70000

### many to one join

In [14]:
df4 = pd.DataFrame({
    "department": ["HR", "IT", "Finance"],
    "supervisor": ["Eve", "Frank", "Grace"]
})

df5 = pd.merge(df1,df4) # default is inner join, on the common column "employee"
df5

  employee department      address supervisor
0    Alice         HR  123 Main St        Eve
1      Bob         IT   456 Elm St      Frank
2  Charlie    Finance   789 Oak St      Grace
3    David    Finance  101 Pine St      Grace

In [22]:
df_left_merged = pd.merge(df1, df2, on="employee", how="left")
df_left_merged

  employee department      address                  skills   salary
0    Alice         HR  123 Main St   [arcitecture, design]  50000.0
1      Bob         IT   456 Elm St  [development, testing]  60000.0
2  Charlie    Finance   789 Oak St              [analysis]  70000.0
3    David    Finance  101 Pine St                     NaN      NaN

In [23]:
df_right_merged = pd.merge(df1, df2, on="employee", how="right")
df_right_merged

  employee department      address                  skills  salary
0    Alice         HR  123 Main St   [arcitecture, design]   50000
1      Bob         IT   456 Elm St  [development, testing]   60000
2  Charlie    Finance   789 Oak St              [analysis]   70000

In [24]:
df_outer_merged = pd.merge(df1, df2, on="employee", how="outer")
df_outer_merged

  employee department      address                  skills   salary
0    Alice         HR  123 Main St   [arcitecture, design]  50000.0
1      Bob         IT   456 Elm St  [development, testing]  60000.0
2  Charlie    Finance   789 Oak St              [analysis]  70000.0
3    David    Finance  101 Pine St                     NaN      NaN